### ISSUE TITLE
Batch Multiple POST requests

### ISSUE THREAD

**Issue by albertvc10** [csotiriou/AFNetworking-PromiseKit#10]
Could just give an example of multiple Post requests? Thanks!

**Comment by csotiriou** [comment]
Tomorrow I will try to push some tests using multiple post requests. However, is there anything specific you are searching for in these examples?? Normally, GET and POST requests should be the same, just use the appropriate function in the AFHTTPRequestOperationManager and AFHTTPSessionManager.
