### ISSUE TITLE
Status Code in .catch(^..) block

### ISSUE THREAD

**Issue by chriscdn** [csotiriou/AFNetworking-PromiseKit#12]
Is there a way to get the web server status code in the `.catch()` block?  Looks good!

**Comment by chriscdn** [comment]
I think I found it...

	NSHTTPURLResponse *response = error.userInfo[AFNetworkingOperationFailingURLResponseErrorKey];
	NSInteger statusCode = response.statusCode;
	NSLog(@"Status Code: %i", statusCode);

**Comment by csotiriou** [comment]
Yes, that is the correct answer. The error propagated by AFNetworking-PromiseKit is the same one that is being produced by AFNetworking.
