### ISSUE TITLE
Broken in Xcode 8.3 

### ISSUE THREAD

**Issue by nrccua-ci-user** [csotiriou/AFNetworking-PromiseKit#22]
This framework uses version 3 of PromiseKit which apparently uses Swift 2.3. Because Xcode 8.3 drops support for Swift 2.3, this framework is no longer usable. Do you have any plans for updating the dependencies to use a newer version of PromiseKit?

**Comment by csotiriou** [comment]
@nrccua-ci-user sorry for the long hiatus, probably you have already found the answer to your question. For what it's worth, I have just released a version 1.0.0 with support for Swift 4/5 and latest versions of Xcode and PromiseKit.
