### ISSUE TITLE
Accessing task object of PMKManifold using when with an array of promises

### ISSUE THREAD

**Issue by mluisbrown** [csotiriou/AFNetworking-PromiseKit#6]
Hi,
Great library. Just one question:

I'm using `AFHTTPSessionManager` and using `when` to make an array of POST requests and wait for their completion:

```objective-c
    NSMutableArray *requests = [NSMutableArray array];

    for (Foo *foo in someFoos) {
        [requests addObject:[self POST:@"http://www.foo.com/api"
                            parameters:params]];
    }

    [PMKPromise when:requests].then(^(NSArray *results) {
    	for (id responseObject in results) {
	    	// do stuff with the responseObject    	
    	}
    	
    	// how do I get to the NSURLSessionDataTask (task) object
    	// which is also in the Promise: fulfiller(PMKManifold(responseObject, task));
    	
    }).catch(^(NSError *error) {
        NSLog(@"Error: %@", error);
    });
```

The `NSArray` that I get in the `then` is an array of `responseObjects`, the first object in the PMKManifold that you create as the fulfiller. How do I access the task object which is also in the PMKManifold?

**Comment by csotiriou** [comment]
Hello,

When a Promise is fulfilled in AFNetworking, the 'then' will contain a responseObject and also a NSURLSessionDataTask. As you do with the base PromiseKit, if you add the `NSURLSessionDataTask *task` argument in the completion block, you will get the task that initiated the request. 

    [self.manager GET:@"sample_url" parameters:nil].then(^(id responseObject, NSURLSessionDataTask *task){
    });

As you can see, the syntax is very flexible.

**Comment by mluisbrown** [comment]
Hi,
Yes, this works when you have a single Promise. However, my question relates to the use of `when` which works with an array of Promises, and in that case the `then` contains an `NSArray *` of results. That `NSArray` contains the `responseObject`s for the requests, but I have no way to get the `NSURLSessionDataTask` objects. I tried adding a second `NSArray *` param to the `then` block but it is passed in empty.

**Comment by csotiriou** [comment]
I now understand what you are trying to say, sorry of not figuring out the first time.

Well, you are right. When using 'when', PromiseKit itself only returns the first object.

In PromiseKit+When, the following code is the reason:

     for (__strong PMKPromise *promise in promises) {
            if (![promise isKindOfClass:[PMKPromise class]])
                promise = [PMKPromise promiseWithValue:promise];
            promise.catch(rejecter(@(ii)));
            promise.then(^(id o){
                [results replacePointerAtIndex:ii withPointer:(__bridge void *)(o ?: [NSNull null])];
                if (--count == 0)
                    fulfiller(results.allObjects);
            });
            ii++;
        }

Notice the "then()"? It only takes into account the first argument.

I only find two possible solutions to this issue:

Either I myself will implement something like 

[myHttpClient when:@[urlString1, urlString2] paramArray:@[dictionary1, dictionary2]] and return a promise there ( I will see if that's possible today) or, I will raise an issue in PromiseKit and see what happens. Given that PromiseKit tries to be agnostic in terms of the arguments being passed on, I can find no straight-forward solution on the part of PromiseKit.

Thanks for raising this issue.

**Comment by csotiriou** [comment]
I just made a commit that will allow you to do the following. 

	self.manager = [[AFHTTPSessionManager alloc] initWithBaseURL:    
	[[NSURL alloc] initWithString:@"http://oramind.com"]];
	self.manager.responseSerializer = [AFHTTPResponseSerializer serializer];

    [self.manager GETMultiple:@[@"/", @"/", @"/", @"/"] parameters:@[@{},@{},@{},@{}]].then(^(NSArray * responsesArray){
        for (NSDictionary *responseDictionary in responsesArray){
            NSLog(@"task description: %@", responseDictionary[kPMKAFResponseTaskKey]);
            NSLog(@"response object description: %@", responseDictionary[kPMKAFResponseObjectKey]);
        }
    });

If you want, you can checkout the master repo and test it. I won't update the Cocoapods repo yet. Does that seem to solve your issue?

It was the only non-invasive solution I could think of for the time being.

**Comment by mluisbrown** [comment]
Thanks! That is a solution that works, all though I can't help thinking that PromiseKit itself should support this internally...

**Comment by csotiriou** [comment]
I'm glad it works for you. I will try to post something into the PromiseKit repo, and see what happens.
