### ISSUE TITLE
Support for PromiseKit 2.0?

### ISSUE THREAD

**Issue by tdansel88** [csotiriou/AFNetworking-PromiseKit#9]
The documentation says that support for PromiseKit 2.0 is currently underway.  Looking at the code, it looks like it's supported already.  Is this a documentation issue or is the 2.0 support shaky?

**Comment by csotiriou** [comment]
Have you used branch 2.0? is it working for you?

**Comment by csotiriou** [comment]
I just pushed a new branch to Cocoapods. It will appear after a while I presume.
